Vagrant.configure("2") do |config|


  # Define Virtual machine
  config.vm.define "domain" do |cfg|
    cfg.vm.box = "server-2019"
    cfg.vm.hostname = "domain"
    cfg.vm.boot_timeout = 600
    cfg.winrm.transport = :plaintext
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: "192.168.38.102", gateway: "192.168.38.1"

    # Provision Virtual Machine
    cfg.vm.provision "shell", path: "./scripts/fix-second-network.ps1", privileged: false, args: "192.168.38.102"
    cfg.vm.provision "shell", path: "./scripts/provision.ps1", privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "./scripts/provision.ps1", privileged: false

    # Provider 
    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "domain.contoso.com"
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--memory", 16000]
      vb.customize ["modifyvm", :id, "--cpus", 4]
      vb.customize ["modifyvm", :id, "--vram", "128"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      #vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end

  # Define Virtual machine
  config.vm.define "kali2-vm" do |cfg|
    cfg.vm.box = "kalirolling"
    cfg.vm.hostname = "kali2-vm"
    cfg.vm.network :private_network, ip: "192.168.38.128"
 
    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      # vb.name = "kali2.contoso.com"
      vb.customize ["modifyvm", :id, "--memory", 4096]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "128"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end

    cfg.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.install_mode = "pip"
    end
  end
end
