Vagrant.configure("2") do |config|


  # Define Virtual machine
  config.vm.define "dc" do |cfg|
    cfg.vm.box = "server-2019"
    cfg.vm.hostname = "dc"
    cfg.vm.boot_timeout = 600
    cfg.winrm.transport = :plaintext
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: "192.168.56.102", gateway: "192.168.56.1"

    # Provision Virtual Machine
    cfg.vm.provision "shell", path: "./scripts/provision.ps1", privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "./scripts/provision.ps1", privileged: false

    # Provider 
    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "dc.contoso.com"
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--memory", 8196]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "128"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      #vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end

  # Define Virtual machine
  config.vm.define "server" do |cfg|
    cfg.vm.box = "server-2019"
    cfg.vm.hostname = "server"
    cfg.vm.boot_timeout = 600
    cfg.winrm.transport = :plaintext
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: "192.168.56.103", gateway: "192.168.56.1"

    # Provision Virtual Machine
    cfg.vm.provision "shell", inline: "Start-Sleep -s 120"
    cfg.vm.provision "shell", path: "./scripts/provision.ps1", privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "./scripts/provision.ps1", privileged: false

    # Provider 
    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "server.contoso.com"
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--memory", 8196]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "128"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      #vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end
end
