# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Define Virtual machine
  config.vm.define "server-2016" do |cfg|
    cfg.vm.box = "server-2016"
    cfg.vm.box = "file://builds/windows-server-2016_virtualbox.box"
    cfg.vm.hostname = "SERVER-2016"
    cfg.vm.boot_timeout = 1200
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 1200
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: "192.168.38.103"

    # Define provider config
    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "WINDOWS-SERVER-2016.local"
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--memory", 4096]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end
end
